extends Node

const CARD_START_SCALE := Vector2(0.3,0.3)
const CARD_SIZE := Vector2(CARD_START_SCALE.x*750, CARD_START_SCALE.y*1050)
const CARD_QUEUE_SCALE := 0.5
const CARD_QUEUE_ADDITIONAL_BUFFER := Vector2(10,0)
